### ISSUE TITLE
When you planning to complete book?

### ISSUE THREAD

**Issue by P9avel** [PacktPublishing/Implementing-Event-driven-Microservices-Architecture-in-.NET6#11]
I am want to buy book. When you planning to complete book?

**Comment by jgarverick** [comment]
It looks like the book will be generally available on March 17th, but I would recommend reaching out to Packt Publishing with any additional questions. Thanks for your interest! Sent from my iPhoneOn Feb 10, 2023, at 8:19 AM, P9avel ***@***.***> wrote:﻿
I am want to buy book. When you planning to complete book?

**Comment by P9avel** [comment]
Many thx for your answer. Waiting book :)

**Comment by rajat-packt** [comment]
Hey @P9avel,

Thank a lot for showing interest in our product!
As Josh has mentioned the book will be available March 17th onwards.

Here are the platforms where you can get yourself a copy: 
[PacktPub - Implementing Event-driven Microservices Architecture in .NET 7](https://www.packtpub.com/product/implementing-event-driven-microservices-architecture-in-net-7/9781803232782?utm_source=github&utm_medium=repository&utm_campaign=)
[Amazon - Implementing Event-driven Microservices Architecture in .NET 7](https://www.amazon.com/dp/1803232781)

We'd love to hear your thoughts on it!
Cheers
